[package]
name = "smoothness"
version = "0.1"
lean_version = "leanprover-community/lean:3.5.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "dbb61ea3a6cd8f68fc2fde3edf12d7995ad1d4ba"}
